### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by okonk** [billyquith/GWork#48] opened 2017-05-27 10:23 UTC
Hi, 

1. I've created a custom tooltip control but I can't figure out how to make the corners rounded and how to add a border colour like the default tooltip. Right now I'm inheriting from Rectangle for my control. Do you know the best way to implement this so I can get rounded corners and a border?

2. It would be nice to have a max length limit on the TextBox, I can submit a PR adding it. How I'm thinking about implementing it is adding SetMaxLength/GetMaxLength methods, and a check inside TextBox::InsertText. One corner case I can think of right now is when the inserted text will go past the limit I think what I will do is input the text up until the limit, the rest will be cut off. Does this sound alright? Is there anything else I'm missing?

3. I'm using Allegro5 and the numpad enter key isn't currently considered an enter key by GWork. What I was thinking of doing is adding to the existing case:

```cpp
case ALLEGRO_KEY_ENTER:
case ALLEGRO_KEY_PAD_ENTER:
    return Gwk::Key::Return;
```

**Comment by billyquith** [comment] 2017-05-30 15:31
> I can't figure out how to make the corners rounded

The tooltip is drawn using this code: https://github.com/billyquith/GWork/blob/gwork/source/gwork/source/ToolTip.cpp#L40

You could try changing the skin? I'd like to add more flexibility to the control rendering at some point; make it more data driven and allow multiple skins, but that's tricky at the moment.

**Comment by billyquith** [comment] 2017-05-30 15:37
>nice to have a max length limit on the TextBox

This could be done by limiting the entry (TextBox), or the holder (Text). Perhaps limiting the entry is better as this allows input control and leaves the UI without limitations otherwise.
https://github.com/billyquith/GWork/blob/gwork/source/gwork/source/Controls/Text.cpp#L64

If you'd like to have a discussion I'd suggest starting another issue, solely about this issue. The problem is these discussions arent threaded and get very confused with multiple topics.

**Comment by billyquith** [comment] 2017-05-30 15:38
> using Allegro5 and the numpad enter key isn't currently considered an enter key by GWork

I can't think of a reason not to do this.

**Comment by billyquith** [comment] 2017-05-30 15:40
As there are multiple changes here: *PR*s are best done a separate branches. I.e. clone _gwork_ branch. Branch to "feature-al5key" (or whatever name), make the change, commit and push to your GH repo, then create PR. Repeat for each change. If you don't do this and just change your mainline all the changes get merged together. - [GitHub workflow](https://guides.github.com/introduction/flow/)

**Comment by okonk** [comment] 2017-06-01 10:56
Thanks. I'll have to dig into the code for the tooltips sometime later, for now my control is working fine, just would have been nice to have.

Created PR #49 for enter key.
Created new issue #50 for textbox discussion.

**Closed as completed** 2017-08-03 08:58 UTC
Labels: question
